# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# plugins:

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

include:
  - _pages
  # - _redirects

# Site settings
title: Remy J. Alan
long-title: Remy J. Alan, author
email: remy.j.alan@gmail.com
description: "Published works and current projects of author, Remy J. Alan"
# description: "Landing page for Remy J. Alan, author of gay literature."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.remyjalan.com" # the base hostname & protocol for your site
timezone: America/New_York
year: 2023
start-year: 2017
sitemap: true

# Social networks
social-username:
  twitter: "@remyauth"
  github: "remyauth"
  medium: "@remyauth"
  instagram: "remyauth"
  mastodon: "remyauth"
  # linkedin: "himatt"
  # pinterest: "mattgreydesign"
  # flickr: "mattgreydesign"
  # spotify: "mattgreydesign"

# Content
image_serve_path: "/images" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  comments: []
  endings: []
  #ignore:
    #envs: [local]
  blanklines: false # boolean - strip blank lines and breaks
  profile: false
  startings: []


# Structure
navigation:
  - title: Elemental
    url: /
  - title: Works
    url: /works
  # - title: News
  #   url: /news
  - title: About
    url: /about
  # - title: Contact
  #   url: /contact

permalink: /:title/

# Configure site collections
collections:
  elemental: 
    output: true
    permalink: /elemental/:path/
  works:
    output: true
    permalink: /works/:path/
  # news:
  #   output: true
  #   permalink: /news/:path/

defaults:
  - scope:
      path: ""
      type: "elemental"
    values:
      layout: "elementbook"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  # - scope: 
  #     path: ""
  #     type: "news"
  #   values:
  #     layout: "news"
